# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: "ubuntu-latest"
variables:
  imageName: 'krishnamsgit/krishna-cv-docker'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: "14.x"
  displayName: "Install Node.js"
- script: |
    yarn
    yarn build
  displayName: "yarn and yarn build"
- task: CopyFiles@2
  inputs:
    SourceFolder: "build/"
    Contents: "**"
    TargetFolder: "$(Build.ArtifactStagingDirectory)"
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: "$(Build.ArtifactStagingDirectory)"
    ArtifactName: "drop"
    publishLocation: "Container"
    
- task: Docker@2
  inputs:
    containerRegistry: 'Docker HuB Krishna'
    repository: '$(imageName)'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    addPipelineData: false
    addBaseImageData: false
- task: Docker@2
  inputs:
    containerRegistry: 'Docker HuB Krishna'
    repository: '$(imageName)'
    command: 'push'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      heroku login
      
      heroku create krishna-pipeline-cv
      
      docker login --username=githubkrish@gmail.com --password=${env:HEROKUTOKEN} registry.heroku.com
      
      heroku container:login
      
      docker tag ${env:IMAGENAME}:${env:BUILD_BUILDID} registry.heroku.com/krishna-pipeline-cv/web
      
      docker push registry.heroku.com/krishna-pipeline-cv/web
      
      heroku container:release web -a krishna-pipeline-cv
